### ISSUE TITLE
[Sample App Request] - iparams-json sample app for Freshsales

### ISSUE THREAD

**Issue by teja-kummarikuntla** [freshworks-developers/configuration-page-samples#10]
### Requirement description
The repository `configuration-page-sample` is subjected to demo multiple ways of building configuration page of Freshworks apps.
The folder [Freshdesk](https://github.com/freshworks-developers/configuration-page-samples/tree/main/freshdesk) is a good example of what is expected to be built for Freshsales.

### Expected solution
create sample apps for Freshsales to demo the usage of
- [ ] iparams-json 

Build and add the sample app to the Freshsales folder
### Resources
- Follow the [Freshdesk](https://github.com/freshworks-developers/configuration-page-samples/tree/main/freshdesk) folder for inspiration.
- [Freshsales documentation](https://developers.freshworks.com/crm/docs/quick-start/)

**Comment by ajithajay** [comment]
Hi @teja-kummarikuntla , all my previous PR approved. Could you please assign this issue?

**Comment by ajithajay** [comment]
Hi @teja-kummarikuntla, my current issue is completed and requested for review. Could you please assign this issue?

**Comment by ajithajay** [comment]
Hi @teja-kummarikuntla @zachjonesnoel ,  Could you please assign this issue?

**Comment by ajithajay** [comment]
Hi @teja-kummarikuntla @zachjonesnoel ,  Could you please assign this issue?

**Comment by ajithajay** [comment]
Hi @teja-kummarikuntla @zachjonesnoel ,  Could you please assign this issue?

**Comment by ajithajay** [comment]
Hi @teja-kummarikuntla @zachjonesnoel ,  Could you please assign this issue?

**Comment by ajithajay** [comment]
Hi @teja-kummarikuntla @zachjonesnoel ,  Could you please assign this issue?

**Comment by ajithajay** [comment]
Hi @teja-kummarikuntla @zachjonesnoel ,  Could you please assign this issue?

**Comment by ajithajay** [comment]
Hi @teja-kummarikuntla @zachjonesnoel ,  Could you please assign this issue?

**Comment by ajithajay** [comment]
Hi @teja-kummarikuntla @zachjonesnoel ,  Could you please assign this issue?

**Comment by ajithajay** [comment]
Hi @teja-kummarikuntla @zachjonesnoel , Please review the PR #16  & update on the same.
