### ISSUE TITLE
Add Readme

### ISSUE THREAD

**Issue by teja-kummarikuntla** [freshworks-developers/configuration-page-samples#11]
Add readme to this repository, briefing the purpose, structure, and navigation. Add reference docs specific to the product folder.

**Comment by harishkotra** [comment]
Is there an existing sample README.md structure that we are looking to achieve? 

I'd like to take this one.

**Comment by saif-shines** [comment]
@harishkotra - Here's an example structure - https://github.com/freshworks-developers/configuration-page-samples/blob/main/freshdesk/iparams-html/README.md

@zachjonesnoel @teja-kummarikuntla - Let's have a template (needs to be templatized first) under `freshworks-developers/.github` so it can be accessible across.

**Comment by harishkotra** [comment]
@teja-kummarikuntla Already sent a PR. Any specific feedback on it?
