### ISSUE TITLE
[Sample App Request] - dynamic_iparams sample app for Freshteam

### ISSUE THREAD

**Issue by teja-kummarikuntla** [freshworks-developers/configuration-page-samples#6]
### Requirement description
The repository `configuration-page-sample` is subjected to demo multiple ways of building configuration page of Freshworks apps.
The folder [Freshdesk](https://github.com/freshworks-developers/configuration-page-samples/tree/main/freshdesk) is a good example of what is expected to be built for Freshteam.

### Expected solution
create sample apps for Freshteam to demo the usage of
- [ ] dynamic_iparams 

Build and add the sample app to the Freshteam folder
### Resources
- Follow the [Freshdesk](https://github.com/freshworks-developers/configuration-page-samples/tree/main/freshdesk) folder for inspiration.
- Freshteam documentation on the [Dynamic Installation page] (https://developers.freshteam.com/docs/installation-parameters/#dynamic_install_page)

**Comment by ajithajay** [comment]
Hi @teja-kummarikuntla  , please assign this one to me.

**Comment by teja-kummarikuntla** [comment]
Awesome, Thanks for taking this up, @ajithajay. I've assigned this to you.

**Comment by ajithajay** [comment]
Hi @teja-kummarikuntla , we need the Freshteam trial account to complete the testing from our end.

When I create a trial account it's automatically blocked.

Account URL: https://ajithr.freshteam.com

Please activate to proceed further

**Comment by ajithajay** [comment]
@teja-kummarikuntla It's done. Please review the Pull Request and let us know.

**Comment by ajithajay** [comment]
Hi @teja-kummarikuntla, Did you get a chance to review the PR?

**Comment by zachjonesnoel** [comment]
Hi @ajithajay, I've reviewed (https://github.com/freshworks-developers/configuration-page-samples/pull/13) and requested a change. In your PR, do reference the issue when you raise it. :)
