### ISSUE TITLE
[Sample App Request] - iparams-json sample app for Freshteam

### ISSUE THREAD

**Issue by teja-kummarikuntla** [freshworks-developers/configuration-page-samples#8]
### Requirement description
The repository `configuration-page-sample` is subjected to demo multiple ways of building configuration page of Freshworks apps.
The folder [Freshdesk](https://github.com/freshworks-developers/configuration-page-samples/tree/main/freshdesk) is a good example of what is expected to be built for Freshteam.

### Expected solution
create sample apps for Freshteam to demo the usage of
- [ ] iparams-json 

Build and add the sample app to the Freshteam folder
### Resources
- Follow the [Freshdesk](https://github.com/freshworks-developers/configuration-page-samples/tree/main/freshdesk) folder for inspiration.
- Freshteam documentation on the [Installation parameters](https://developers.freshteam.com/docs/installation-parameters/)

**Comment by ajithajay** [comment]
Hi @teja-kummarikuntla  , please assign this one to me.

**Comment by ajithajay** [comment]
Hi @teja-kummarikuntla , my current [issue](https://github.com/freshworks-developers/configuration-page-samples/issues/9) is completed and requested for review. Could you please assign this issue?

**Comment by ajithajay** [comment]
Hi @teja-kummarikuntla , all my previous PR approved. Could you please assign this issue?

**Comment by ajithajay** [comment]
Hi @teja-kummarikuntla  Please review the [PR 15](https://github.com/freshworks-developers/configuration-page-samples/pull/15) and update on the same.

**Comment by ajithajay** [comment]
Hi @teja-kummarikuntla @zachjonesnoel  Please review the [PR] 15(https://github.com/freshworks-developers/configuration-page-samples/pull/15 ) and update on the same.
