### ISSUE TITLE
[Sample App Request] - dynamic_iparams sample app for Freshsales

### ISSUE THREAD

**Issue by teja-kummarikuntla** [freshworks-developers/configuration-page-samples#9]
### Requirement description
The repository `configuration-page-sample` is subjected to demo multiple ways of building configuration page of Freshworks apps.
The folder [Freshdesk](https://github.com/freshworks-developers/configuration-page-samples/tree/main/freshdesk) is a good example of what is expected to be built for Freshsales.

### Expected solution
create sample apps for Frshsales to demo the usage of
- [ ] dynamic_iparams 

Build and add the sample app to the Freshsales folder
### Resources
- Follow the [Freshdesk](https://github.com/freshworks-developers/configuration-page-samples/tree/main/freshdesk) folder for inspiration.
- [Freshsales documentation](https://developers.freshworks.com/crm/docs/quick-start/)

**Comment by ajithajay** [comment]
Hi @teja-kummarikuntla , please assign this one to me.

**Comment by teja-kummarikuntla** [comment]
Hey @ajithajay , thanks for showing interest. I'm assigning this issue to you.
Once done with this, we can assign you to the other issues you requested for, just that others can take up while you're working on this by any chance.

**Comment by ajithajay** [comment]
@teja-kummarikuntla Please review the PR [#14](https://github.com/freshworks-developers/configuration-page-samples/pull/14) and update on the same.
